INSERT INTO department(department_name)
VALUES('Seasonal');
insert into department (department_name) values ('Gardening');
insert into department (department_name) values ('Poultry');
insert into department (department_name) values ('Deli');
insert into department (department_name) values ('Computers');
insert into department (department_name) values ('Hardware');
insert into department (department_name) values ('Florist');
insert into department (department_name) values ('Gaming');
insert into department (department_name) values ('Automotive');

insert into product (name, department_id) values ('Shiro Miso', 3);
insert into product (name, department_id) values ('Ecolab - Orange Frc, Cleaner', 4);
insert into product (name, department_id) values ('Pork - Loin, Center Cut', 9);
insert into product (name, department_id) values ('Wine - Cave Springs Dry Riesling', 7);
insert into product (name, department_id) values ('Oneshot Automatic Soap System', 8);
insert into product (name, department_id) values ('Carrots - Mini, Stem On', 1);
insert into product (name, department_id) values ('Baking Soda', 1);
insert into product (name, department_id) values ('Banana - Green', 8);
insert into product (name, department_id) values ('Pasta - Fettuccine, Dry', 5);
insert into product (name, department_id) values ('Glass - Juice Clear 5oz 55005', 4);
insert into product (name, department_id) values ('Soup - Beef, Base Mix', 4);
insert into product (name, department_id) values ('Cod - Black Whole Fillet', 5);
insert into product (name, department_id) values ('Cheese - Grie Des Champ', 6);
insert into product (name, department_id) values ('Rappini - Andy Boy', 6);
insert into product (name, department_id) values ('Pepper - Julienne, Frozen', 2);
insert into product (name, department_id) values ('Salmon - Atlantic, Fresh, Whole', 1);
insert into product (name, department_id) values ('Muffin - Mix - Bran And Maple 15l', 2);
insert into product (name, department_id) values ('Beer - Mill St Organic', 9);
insert into product (name, department_id) values ('Nut - Almond, Blanched, Sliced', 5);
insert into product (name, department_id) values ('Nut - Cashews, Whole, Raw', 2);
insert into product (name, department_id) values ('Sea Urchin', 9);
insert into product (name, department_id) values ('Pork - European Side Bacon', 5);
insert into product (name, department_id) values ('Towel Dispenser', 9);
insert into product (name, department_id) values ('Tarragon - Fresh', 1);
insert into product (name, department_id) values ('Pepper - Chilli Seeds Mild', 5);
insert into product (name, department_id) values ('Milk - 1%', 9);
insert into product (name, department_id) values ('Chickhen - Chicken Phyllo', 6);
insert into product (name, department_id) values ('Transfer Sheets', 8);
insert into product (name, department_id) values ('Olives - Morracan Dired', 2);
insert into product (name, department_id) values ('Juice - Mango', 8);
insert into product (name, department_id) values ('Wine - Masi Valpolocell', 9);
insert into product (name, department_id) values ('Hot Chocolate - Individual', 4);
insert into product (name, department_id) values ('Muffin - Zero Transfat', 5);
insert into product (name, department_id) values ('Chocolate - Semi Sweet', 1);
insert into product (name, department_id) values ('Cookies Cereal Nut', 3);
insert into product (name, department_id) values ('Hot White Chocolate - Individual', 6);
insert into product (name, department_id) values ('Pasta - Fettuccine', 5);
insert into product (name, department_id) values ('Mousse - Mango', 5);
insert into product (name, department_id) values ('Potatoes - Yukon Gold 5 Oz', 2);
insert into product (name, department_id) values ('Hagen Daza - Dk Choocolate', 3);
insert into product (name, department_id) values ('Ice Cream - Life Savers', 4);
insert into product (name, department_id) values ('Mushroom - Shitake, Fresh', 4);
insert into product (name, department_id) values ('Eggplant Italian', 5);
insert into product (name, department_id) values ('Nut - Walnut, Pieces', 5);
insert into product (name, department_id) values ('Juice - Apple 284ml', 7);
insert into product (name, department_id) values ('Celery Root', 9);
insert into product (name, department_id) values ('Pork - Bacon, Sliced', 2);
insert into product (name, department_id) values ('Pasta - Fett Alfredo, Single Serve', 5);
insert into product (name, department_id) values ('Lettuce - Lolla Rosa', 2);
insert into product (name, department_id) values ('Kippers - Smoked', 4);
insert into product (name, department_id) values ('Glaze - Clear', 7);
insert into product (name, department_id) values ('Nescafe - Frothy French Vanilla', 4);
insert into product (name, department_id) values ('Tea - Lemon Scented', 6);
insert into product (name, department_id) values ('Lamb - Whole, Fresh', 2);
insert into product (name, department_id) values ('Country Roll', 7);
insert into product (name, department_id) values ('Lime Cordial - Roses', 5);
insert into product (name, department_id) values ('Cookies - Assorted', 7);
insert into product (name, department_id) values ('Beer - True North Strong Ale', 2);
insert into product (name, department_id) values ('Juice - Propel Sport', 4);
insert into product (name, department_id) values ('The Pop Shoppe Pinapple', 9);
insert into product (name, department_id) values ('Cup - 8oz Coffee Perforated', 6);
insert into product (name, department_id) values ('Flavouring Vanilla Artificial', 8);
insert into product (name, department_id) values ('Cake Slab', 7);
insert into product (name, department_id) values ('Chocolate Bar - Smarties', 4);
insert into product (name, department_id) values ('Rice - Wild', 5);
insert into product (name, department_id) values ('V8 Pet', 3);
insert into product (name, department_id) values ('Chips - Potato Jalapeno', 4);
insert into product (name, department_id) values ('Dried Cherries', 8);
insert into product (name, department_id) values ('Soup Campbells Beef', 7);
insert into product (name, department_id) values ('Cheese - Goat', 2);
insert into product (name, department_id) values ('Sauce - Vodka Blush', 9);
insert into product (name, department_id) values ('Chivas Regal - 12 Year Old', 2);
insert into product (name, department_id) values ('Foam Dinner Plate', 7);
insert into product (name, department_id) values ('Monkfish - Fresh', 1);
insert into product (name, department_id) values ('Water Chestnut - Canned', 1);
insert into product (name, department_id) values ('Pork - Loin, Boneless', 7);
insert into product (name, department_id) values ('Seabream Whole Farmed', 2);
insert into product (name, department_id) values ('Chicken - Leg / Back Attach', 9);
insert into product (name, department_id) values ('Appetizer - Southwestern', 7);
insert into product (name, department_id) values ('Butcher Twine 4r', 1);
insert into product (name, department_id) values ('Wine - Hardys Bankside Shiraz', 7);
insert into product (name, department_id) values ('Cranberry Foccacia', 8);
insert into product (name, department_id) values ('Doilies - 8, Paper', 1);
insert into product (name, department_id) values ('Sugar - Monocystal / Rock', 2);
insert into product (name, department_id) values ('Lemonade - Kiwi, 591 Ml', 8);
insert into product (name, department_id) values ('Flour - Rye', 9);
insert into product (name, department_id) values ('Beer - Sleemans Honey Brown', 3);
insert into product (name, department_id) values ('Bread - Pita', 4);
insert into product (name, department_id) values ('Soup Campbells Turkey Veg.', 3);
insert into product (name, department_id) values ('Soup - Campbells Pasta Fagioli', 7);
insert into product (name, department_id) values ('Potatoes - Yukon Gold, 80 Ct', 7);
insert into product (name, department_id) values ('Shrimp - 150 - 250', 3);
insert into product (name, department_id) values ('Wine - Balbach Riverside', 3);
insert into product (name, department_id) values ('Lettuce - Mini Greens, Whole', 2);
insert into product (name, department_id) values ('Lettuce - Treviso', 3);
insert into product (name, department_id) values ('Longos - Lasagna Beef', 1);
insert into product (name, department_id) values ('Capicola - Hot', 3);
insert into product (name, department_id) values ('Trout - Smoked', 1);
insert into product (name, department_id) values ('Chicken Breast Halal', 4);
insert into product (name, department_id) values ('Cup - 4oz Translucent', 8);
insert into product (name, department_id) values ('Sauce - Balsamic Viniagrette', 2);
insert into product (name, department_id) values ('Mushroom - Trumpet, Dry', 1);
insert into product (name, department_id) values ('Sauce - Gravy, Au Jus, Mix', 5);
insert into product (name, department_id) values ('Wine - Fume Blanc Fetzer', 9);
insert into product (name, department_id) values ('Sugar Thermometer', 3);
insert into product (name, department_id) values ('Bag Clear 10 Lb', 1);
insert into product (name, department_id) values ('Carbonated Water - Raspberry', 5);
insert into product (name, department_id) values ('Soup Campbells - Tomato Bisque', 8);
insert into product (name, department_id) values ('Pastry - Chocolate Marble Tea', 3);
insert into product (name, department_id) values ('Icecream - Dibs', 4);
insert into product (name, department_id) values ('Sugar - White Packet', 1);
insert into product (name, department_id) values ('Flower - Potmums', 7);
insert into product (name, department_id) values ('Saskatoon Berries - Frozen', 2);
insert into product (name, department_id) values ('Arctic Char - Fillets', 5);
insert into product (name, department_id) values ('Mahi Mahi', 7);
insert into product (name, department_id) values ('Wine - Sake', 5);
insert into product (name, department_id) values ('Ginger - Fresh', 6);
insert into product (name, department_id) values ('Marzipan 50/50', 9);
insert into product (name, department_id) values ('Pate Pans Yellow', 2);
insert into product (name, department_id) values ('Hickory Smoke, Liquid', 2);
insert into product (name, department_id) values ('Langers - Mango Nectar', 3);
insert into product (name, department_id) values ('Sloe Gin - Mcguinness', 7);
insert into product (name, department_id) values ('Lamb - Loin Chops', 4);
insert into product (name, department_id) values ('Lemon Grass', 8);
insert into product (name, department_id) values ('Everfresh Products', 5);
insert into product (name, department_id) values ('Turkey - Whole, Fresh', 9);
insert into product (name, department_id) values ('Island Oasis - Mango Daiquiri', 9);
insert into product (name, department_id) values ('Rice Wine - Aji Mirin', 9);
insert into product (name, department_id) values ('Silicone Paper 16.5x24', 4);
insert into product (name, department_id) values ('Red Snapper - Fillet, Skin On', 4);
insert into product (name, department_id) values ('Veal - Inside', 3);
insert into product (name, department_id) values ('Pepper - Red Thai', 3);
insert into product (name, department_id) values ('Onions - White', 2);
insert into product (name, department_id) values ('Wine - Harrow Estates, Vidal', 2);
insert into product (name, department_id) values ('Pastry - Baked Cinnamon Stick', 6);
insert into product (name, department_id) values ('Crab - Back Fin Meat, Canned', 8);
insert into product (name, department_id) values ('Tuna - Bluefin', 4);
insert into product (name, department_id) values ('Pastry - Baked Scones - Mini', 2);
insert into product (name, department_id) values ('Pork Loin Bine - In Frenched', 2);
insert into product (name, department_id) values ('Beef - Rouladin, Sliced', 4);
insert into product (name, department_id) values ('Easy Off Oven Cleaner', 1);
insert into product (name, department_id) values ('Pork - Inside', 5);
insert into product (name, department_id) values ('Appetizer - Lobster Phyllo Roll', 3);
insert into product (name, department_id) values ('Grenadine', 4);
insert into product (name, department_id) values ('Ham - Cooked Italian', 7);
insert into product (name, department_id) values ('Jam - Raspberry', 5);
insert into product (name, department_id) values ('Pork - Loin', 6);
insert into product (name, department_id) values ('Lotus Root', 1);
insert into product (name, department_id) values ('Anchovy Paste - 56 G Tube', 8);
insert into product (name, department_id) values ('Bread - Assorted Rolls', 8);
insert into product (name, department_id) values ('Star Anise, Whole', 6);
insert into product (name, department_id) values ('Soup - Knorr, Classic Can. Chili', 8);
insert into product (name, department_id) values ('Ham - Black Forest', 5);
insert into product (name, department_id) values ('Sauce - Apple, Unsweetened', 7);
insert into product (name, department_id) values ('Beef - Chuck, Boneless', 1);
insert into product (name, department_id) values ('Beef Striploin Aaa', 7);
insert into product (name, department_id) values ('Fib N9 - Prague Powder', 7);
insert into product (name, department_id) values ('Blueberries - Frozen', 9);
insert into product (name, department_id) values ('Roe - Lump Fish, Black', 3);
insert into product (name, department_id) values ('Wine - White, Colubia Cresh', 4);
insert into product (name, department_id) values ('Beef - Inside Round', 5);
insert into product (name, department_id) values ('Monkfish Fresh - Skin Off', 4);
insert into product (name, department_id) values ('Wanton Wrap', 7);
insert into product (name, department_id) values ('Longos - Grilled Salmon With Bbq', 5);
insert into product (name, department_id) values ('Flour - Chickpea', 4);
insert into product (name, department_id) values ('Mushroom - Porcini, Dry', 9);
insert into product (name, department_id) values ('Pork - Back, Long Cut, Boneless', 1);
insert into product (name, department_id) values ('Sausage - Liver', 9);
insert into product (name, department_id) values ('Cheese - Cheddar With Claret', 3);
insert into product (name, department_id) values ('Scallop - St. Jaques', 4);
insert into product (name, department_id) values ('Quail - Whole, Boneless', 1);
insert into product (name, department_id) values ('Beef - Diced', 6);
insert into product (name, department_id) values ('Chicken - Ground', 6);
insert into product (name, department_id) values ('Bread - Focaccia Quarter', 2);
insert into product (name, department_id) values ('Pomello', 7);
insert into product (name, department_id) values ('Rabbit - Whole', 8);
insert into product (name, department_id) values ('Flower - Commercial Bronze', 7);
insert into product (name, department_id) values ('Wine - Trimbach Pinot Blanc', 2);
insert into product (name, department_id) values ('Wine - Red, Cabernet Merlot', 9);
insert into product (name, department_id) values ('Squid - U - 10 Thailand', 8);
insert into product (name, department_id) values ('Watercress', 4);
insert into product (name, department_id) values ('Pie Shell - 9', 5);
insert into product (name, department_id) values ('Ginsing - Fresh', 3);
insert into product (name, department_id) values ('Longos - Grilled Veg Sandwiches', 2);
insert into product (name, department_id) values ('Duck - Breast', 2);
insert into product (name, department_id) values ('Long Island Ice Tea', 8);
insert into product (name, department_id) values ('Cheese - Cheddar, Old White', 2);
insert into product (name, department_id) values ('Broom Handle', 2);
insert into product (name, department_id) values ('Pecan Raisin - Tarts', 5);
insert into product (name, department_id) values ('Bread - French Stick', 8);
insert into product (name, department_id) values ('Spinach - Frozen', 4);
insert into product (name, department_id) values ('Sobe - Green Tea', 7);
insert into product (name, department_id) values ('Nori Sea Weed', 2);
insert into product (name, department_id) values ('Cheese - Feta', 7);
insert into product (name, department_id) values ('Cheese - Goat With Herbs', 1);
insert into product (name, department_id) values ('Bacardi Breezer - Tropical', 2);
insert into product (name, department_id) values ('Mushroom - White Button', 7);
insert into product (name, department_id) values ('Crab - Claws, Snow 16 - 24', 1);
insert into product (name, department_id) values ('Garlic - Peeled', 1);
insert into product (name, department_id) values ('Turkey - Breast, Boneless Sk On', 4);
insert into product (name, department_id) values ('Soap - Hand Soap', 8);
insert into product (name, department_id) values ('Soup - Campbells Chili', 4);
insert into product (name, department_id) values ('Towel Multifold', 8);
insert into product (name, department_id) values ('Coffee - Flavoured', 3);
insert into product (name, department_id) values ('Tomatoes - Plum, Canned', 6);
insert into product (name, department_id) values ('Ham - Cooked Bayonne Tinned', 2);
insert into product (name, department_id) values ('Bread - French Baquette', 7);
insert into product (name, department_id) values ('Cabbage - Green', 3);
insert into product (name, department_id) values ('Vinegar - Red Wine', 2);
insert into product (name, department_id) values ('Peas Snow', 6);
insert into product (name, department_id) values ('Bread - Triangle White', 3);
insert into product (name, department_id) values ('Nut - Pistachio, Shelled', 5);
insert into product (name, department_id) values ('Nutmeg - Ground', 4);
insert into product (name, department_id) values ('Shrimp - Black Tiger 26/30', 3);
insert into product (name, department_id) values ('Ezy Change Mophandle', 9);
insert into product (name, department_id) values ('Soup - Base Broth Beef', 8);
insert into product (name, department_id) values ('Mushroom - Chantrelle, Fresh', 1);
insert into product (name, department_id) values ('Stainless Steel Cleaner Vision', 9);
insert into product (name, department_id) values ('Relish', 1);
insert into product (name, department_id) values ('Extract - Vanilla,artificial', 1);
insert into product (name, department_id) values ('Pasta - Bauletti, Chicken White', 4);
insert into product (name, department_id) values ('Ecolab - Balanced Fusion', 7);
insert into product (name, department_id) values ('Wine - Red, Metus Rose', 6);
insert into product (name, department_id) values ('Appetizer - Cheese Bites', 7);
insert into product (name, department_id) values ('Chocolate - Compound Coating', 1);
insert into product (name, department_id) values ('Oranges - Navel, 72', 5);
insert into product (name, department_id) values ('Bread - Dark Rye', 9);
insert into product (name, department_id) values ('Tea - Herbal I Love Lemon', 8);
insert into product (name, department_id) values ('Bar Bran Honey Nut', 9);
insert into product (name, department_id) values ('Beer - Steamwhistle', 6);
insert into product (name, department_id) values ('Kellogs All Bran Bars', 5);
insert into product (name, department_id) values ('Cake - Mini Cheesecake', 1);
insert into product (name, department_id) values ('Corn - Mini', 8);
insert into product (name, department_id) values ('Catfish - Fillets', 6);
insert into product (name, department_id) values ('Bread - Crumbs, Bulk', 1);
insert into product (name, department_id) values ('Tomatoes - Vine Ripe, Yellow', 2);
insert into product (name, department_id) values ('Pail With Metal Handle 16l White', 1);
insert into product (name, department_id) values ('Foil - Round Foil', 8);
insert into product (name, department_id) values ('Bread - Sticks, Thin, Plain', 1);
insert into product (name, department_id) values ('Syrup - Monin, Swiss Choclate', 9);
insert into product (name, department_id) values ('Langers - Cranberry Cocktail', 2);
insert into product (name, department_id) values ('Cheese - Montery Jack', 3);
insert into product (name, department_id) values ('Wine - Niagara,vqa Reisling', 8);
insert into product (name, department_id) values ('Wine - Piper Heidsieck Brut', 9);
insert into product (name, department_id) values ('The Pop Shoppe - Grape', 2);
insert into product (name, department_id) values ('Soup Campbells - Italian Wedding', 1);
insert into product (name, department_id) values ('Pie Shells 10', 8);
insert into product (name, department_id) values ('Sobe - Lizard Fuel', 2);
insert into product (name, department_id) values ('Cleaner - Comet', 1);
insert into product (name, department_id) values ('Lettuce - Escarole', 2);
insert into product (name, department_id) values ('Tomatoes Tear Drop', 3);
insert into product (name, department_id) values ('Cheese - Oka', 6);
insert into product (name, department_id) values ('Ecolab - Hobart Upr Prewash Arm', 9);
insert into product (name, department_id) values ('Stock - Beef, White', 7);
insert into product (name, department_id) values ('Brandy - Orange, Mc Guiness', 9);
insert into product (name, department_id) values ('Pasta - Orecchiette', 2);
insert into product (name, department_id) values ('Appetizer - Assorted Box', 7);
insert into product (name, department_id) values ('Chocolate Bar - Oh Henry', 4);
insert into product (name, department_id) values ('Molasses - Fancy', 1);
insert into product (name, department_id) values ('Onions - Cooking', 4);
insert into product (name, department_id) values ('Lobster - Cooked', 8);
insert into product (name, department_id) values ('Lamb - Rack', 9);
insert into product (name, department_id) values ('Flour Dark Rye', 7);
insert into product (name, department_id) values ('Emulsifier', 1);
insert into product (name, department_id) values ('Salt - Sea', 7);
insert into product (name, department_id) values ('Rum - Light, Captain Morgan', 5);
insert into product (name, department_id) values ('Tomatoes - Orange', 8);
insert into product (name, department_id) values ('Chilli Paste, Hot Sambal Oelek', 5);
insert into product (name, department_id) values ('Sprouts - Corn', 6);
insert into product (name, department_id) values ('Sour Puss Sour Apple', 3);
insert into product (name, department_id) values ('Muffin Mix - Banana Nut', 4);
insert into product (name, department_id) values ('Pepper - Pablano', 3);
insert into product (name, department_id) values ('Ice Cream - Super Sandwich', 3);
insert into product (name, department_id) values ('Table Cloth 62x114 White', 7);
insert into product (name, department_id) values ('Bread - Ciabatta Buns', 2);
insert into product (name, department_id) values ('Wine - Prosecco Valdobiaddene', 4);
insert into product (name, department_id) values ('Towel - Roll White', 3);
insert into product (name, department_id) values ('Icecream - Dstk Strw Chseck', 5);
insert into product (name, department_id) values ('Onions - Dried, Chopped', 2);
insert into product (name, department_id) values ('Cookies Almond Hazelnut', 3);
insert into product (name, department_id) values ('Flour - Whole Wheat', 8);
insert into product (name, department_id) values ('Apple - Delicious, Golden', 2);
insert into product (name, department_id) values ('Muffin Mix - Lemon Cranberry', 9);
insert into product (name, department_id) values ('Cod - Salted, Boneless', 5);
insert into product (name, department_id) values ('Soup - Knorr, French Onion', 1);
insert into product (name, department_id) values ('Vegetable - Base', 6);
insert into product (name, department_id) values ('Walkers Special Old Whiskey', 6);
insert into product (name, department_id) values ('Wine - White, French Cross', 3);
insert into product (name, department_id) values ('Prunes - Pitted', 9);
insert into product (name, department_id) values ('Milk - Homo', 4);
insert into product (name, department_id) values ('Yogurt - Raspberry, 175 Gr', 7);
insert into product (name, department_id) values ('Chicken - Whole Fryers', 2);
insert into product (name, department_id) values ('Brocolinni - Gaylan, Chinese', 6);
insert into product (name, department_id) values ('Beef - Chuck', 9);
insert into product (name, department_id) values ('Breadfruit', 9);
insert into product (name, department_id) values ('Iced Tea - Lemon, 460 Ml', 4);
insert into product (name, department_id) values ('Wine - Ej Gallo Sierra Valley', 4);
insert into product (name, department_id) values ('Peach - Halves', 2);
insert into product (name, department_id) values ('Chickensplit Half', 6);
insert into product (name, department_id) values ('Pastry - Chocolate Tea', 9);
insert into product (name, department_id) values ('Dome Lid Clear P92008h', 1);
insert into product (name, department_id) values ('Pea - Snow', 3);
insert into product (name, department_id) values ('Port - 74 Brights', 1);
insert into product (name, department_id) values ('Sugar - Fine', 5);
insert into product (name, department_id) values ('Soup - French Onion, Dry', 3);
insert into product (name, department_id) values ('Beef - Bones, Cut - Up', 5);
insert into product (name, department_id) values ('Cocoa Powder - Dutched', 6);
insert into product (name, department_id) values ('Shrimp - Prawn', 8);
insert into product (name, department_id) values ('Lemon Pepper', 5);
insert into product (name, department_id) values ('Cookies Cereal', 6);
insert into product (name, department_id) values ('Jolt Cola', 6);
insert into product (name, department_id) values ('Icecream - Dstk Super Cone', 1);
insert into product (name, department_id) values ('Sambuca - Ramazzotti', 2);
insert into product (name, department_id) values ('Beef - Kindney, Whole', 4);
insert into product (name, department_id) values ('Chicken - Leg, Boneless', 1);
insert into product (name, department_id) values ('Cheese - Gouda Smoked', 7);
insert into product (name, department_id) values ('Lamb - Ground', 6);
insert into product (name, department_id) values ('Beef Cheek Fresh', 9);
insert into product (name, department_id) values ('Wine - Mondavi Coastal Private', 8);
insert into product (name, department_id) values ('Ice Cream - Fudge Bars', 1);
insert into product (name, department_id) values ('Water - Mineral, Natural', 5);
insert into product (name, department_id) values ('Muffin', 6);
insert into product (name, department_id) values ('Flour - Fast / Rapid', 4);
insert into product (name, department_id) values ('Beer - Paulaner Hefeweisse', 2);
insert into product (name, department_id) values ('V8 Splash Strawberry Banana', 3);
insert into product (name, department_id) values ('Cream - 18%', 1);
insert into product (name, department_id) values ('Juice - Lagoon Mango', 4);
insert into product (name, department_id) values ('Tequila - Sauza Silver', 8);
insert into product (name, department_id) values ('Tea Peppermint', 1);
insert into product (name, department_id) values ('Pepper Squash', 8);
insert into product (name, department_id) values ('Wine - Magnotta - Cab Franc', 2);
insert into product (name, department_id) values ('Cocoa Powder', 6);
insert into product (name, department_id) values ('Muffin Hinge Container 6', 4);
insert into product (name, department_id) values ('Pork - Back, Short Cut, Boneless', 8);
insert into product (name, department_id) values ('Beef - Bones, Marrow', 2);
insert into product (name, department_id) values ('Sweet Pea Sprouts', 3);
insert into product (name, department_id) values ('Onions - Cippolini', 6);
insert into product (name, department_id) values ('Sole - Iqf', 3);
insert into product (name, department_id) values ('Flavouring - Raspberry', 7);
insert into product (name, department_id) values ('Soup - Knorr, Country Bean', 1);
insert into product (name, department_id) values ('Lamb Rack - Ontario', 3);
insert into product (name, department_id) values ('Pheasants - Whole', 3);
insert into product (name, department_id) values ('Mushroom - Shitake, Dry', 1);
insert into product (name, department_id) values ('Potatoes - Parissienne', 3);
insert into product (name, department_id) values ('Juice - Orange, 341 Ml', 2);
insert into product (name, department_id) values ('Champagne - Brights, Dry', 1);
insert into product (name, department_id) values ('Energy Drink - Redbull 355ml', 5);
insert into product (name, department_id) values ('Bread - Raisin Walnut Pull', 8);
insert into product (name, department_id) values ('Garlic', 4);
insert into product (name, department_id) values ('Pie Shell - 5', 8);
insert into product (name, department_id) values ('Tea - Jasmin Green', 4);
insert into product (name, department_id) values ('Oil - Olive', 1);
insert into product (name, department_id) values ('Cheese - Colby', 2);
insert into product (name, department_id) values ('Wine - Gato Negro Cabernet', 7);
insert into product (name, department_id) values ('Irish Cream - Butterscotch', 3);
insert into product (name, department_id) values ('Tamarillo', 9);
insert into product (name, department_id) values ('Chocolate - Feathers', 8);
insert into product (name, department_id) values ('Milk - Chocolate 500ml', 8);
insert into product (name, department_id) values ('Fond - Neutral', 3);
insert into product (name, department_id) values ('Ice - Clear, 300 Lb For Carving', 6);
insert into product (name, department_id) values ('Sauce - Salsa', 7);
insert into product (name, department_id) values ('Wine - Redchard Merritt', 3);
insert into product (name, department_id) values ('Nut - Pine Nuts, Whole', 2);
insert into product (name, department_id) values ('Foam Espresso Cup Plain White', 9);
insert into product (name, department_id) values ('Pears - Anjou', 9);
insert into product (name, department_id) values ('Dooleys Toffee', 5);
insert into product (name, department_id) values ('Oil - Olive, Extra Virgin', 7);
insert into product (name, department_id) values ('Cookies', 6);
insert into product (name, department_id) values ('Wine - Puligny Montrachet A.', 9);
insert into product (name, department_id) values ('Coriander - Ground', 5);
insert into product (name, department_id) values ('Trout Rainbow Whole', 2);
insert into product (name, department_id) values ('Muffin - Mix - Mango Sour Cherry', 5);
insert into product (name, department_id) values ('Wine - Red, Lurton Merlot De', 3);
insert into product (name, department_id) values ('Pears - Bartlett', 1);
insert into product (name, department_id) values ('Tuna - Yellowfin', 5);
insert into product (name, department_id) values ('Worcestershire Sauce', 3);
insert into product (name, department_id) values ('Olives - Kalamata', 5);
insert into product (name, department_id) values ('Soupfoamcont12oz 112con', 3);
insert into product (name, department_id) values ('Cheese - Le Cheve Noir', 1);
insert into product (name, department_id) values ('Syrup - Monin, Amaretta', 6);
insert into product (name, department_id) values ('Jolt Cola - Electric Blue', 9);
insert into product (name, department_id) values ('Wine - Chateau Bonnet', 7);
insert into product (name, department_id) values ('Pie Shells', 4);
insert into product (name, department_id) values ('Poppy Seed', 5);
insert into product (name, department_id) values ('Olive - Spread Tapenade', 8);
insert into product (name, department_id) values ('Yogurt - Cherry, 175 Gr', 5);
insert into product (name, department_id) values ('Plaintain', 8);
insert into product (name, department_id) values ('Wine - Puligny Montrachet.', 5);
insert into product (name, department_id) values ('Soup Campbells Split Pea And Ham', 7);
insert into product (name, department_id) values ('Catfish', 9);
insert into product (name, department_id) values ('Pasta - Gnocchi, Potato', 7);
insert into product (name, department_id) values ('Danishes - Mini Raspberry', 3);
insert into product (name, department_id) values ('Gingerale - Diet - Schweppes', 4);
insert into product (name, department_id) values ('Chevere Logs', 8);
insert into product (name, department_id) values ('Wine - Alicanca Vinho Verde', 5);
insert into product (name, department_id) values ('Cheese - Swiss Sliced', 8);
insert into product (name, department_id) values ('Tart Shells - Savory, 4', 7);
insert into product (name, department_id) values ('Pancetta', 9);
insert into product (name, department_id) values ('Mushrooms - Honey', 5);
insert into product (name, department_id) values ('Vol Au Vents', 7);
insert into product (name, department_id) values ('Tea - Green', 3);
insert into product (name, department_id) values ('Dc - Sakura Fu', 8);
insert into product (name, department_id) values ('Appetizer - Crab And Brie', 8);
insert into product (name, department_id) values ('Pork - Loin, Bone - In', 6);
insert into product (name, department_id) values ('Nougat - Paste / Cream', 4);
insert into product (name, department_id) values ('Pasta - Linguini, Dry', 7);
insert into product (name, department_id) values ('Dr. Pepper - 355ml', 9);
insert into product (name, department_id) values ('Calypso - Black Cherry Lemonade', 2);
insert into product (name, department_id) values ('Cheese - Havarti, Salsa', 5);
insert into product (name, department_id) values ('Turkey - Breast, Bone - In', 1);
insert into product (name, department_id) values ('Veal - Brisket, Provimi, Bone - In', 6);
insert into product (name, department_id) values ('Muffin - Carrot Individual Wrap', 1);
insert into product (name, department_id) values ('Jello - Assorted', 9);
insert into product (name, department_id) values ('Beef - Top Sirloin', 9);
insert into product (name, department_id) values ('Bread Ww Cluster', 9);
insert into product (name, department_id) values ('Soup Campbells Beef With Veg', 5);
insert into product (name, department_id) values ('Mackerel Whole Fresh', 8);
insert into product (name, department_id) values ('Crackers Cheez It', 5);
insert into product (name, department_id) values ('Veal - Heart', 7);
insert into product (name, department_id) values ('Croissants Thaw And Serve', 8);
insert into product (name, department_id) values ('Yoghurt Tubes', 8);
insert into product (name, department_id) values ('Red Snapper - Fresh, Whole', 7);
insert into product (name, department_id) values ('Cheese - Comte', 3);
insert into product (name, department_id) values ('Alize Sunset', 5);
insert into product (name, department_id) values ('Pepper - Paprika, Hungarian', 4);
insert into product (name, department_id) values ('Beef - Ground, Extra Lean, Fresh', 1);
insert into product (name, department_id) values ('Juice - Ocean Spray Cranberry', 2);
insert into product (name, department_id) values ('Papayas', 1);
insert into product (name, department_id) values ('Cake - Lemon Chiffon', 9);
insert into product (name, department_id) values ('Cheese - Wine', 5);
insert into product (name, department_id) values ('Wiberg Cure', 3);
insert into product (name, department_id) values ('Cheese - Augre Des Champs', 7);
insert into product (name, department_id) values ('Oil - Truffle, Black', 1);
insert into product (name, department_id) values ('Silicone Parch. 16.3x24.3', 8);
insert into product (name, department_id) values ('Capers - Pickled', 7);
insert into product (name, department_id) values ('Lobak', 7);
insert into product (name, department_id) values ('Currants', 7);
insert into product (name, department_id) values ('Plasticspoonblack', 2);
insert into product (name, department_id) values ('Kellogs Special K Cereal', 6);
insert into product (name, department_id) values ('Nut - Hazelnut, Ground, Natural', 2);
insert into product (name, department_id) values ('Bread - Mini Hamburger Bun', 9);
insert into product (name, department_id) values ('Bread - Multigrain Oval', 7);
insert into product (name, department_id) values ('Coffee - Irish Cream', 7);
insert into product (name, department_id) values ('Muffin Mix - Carrot', 7);
insert into product (name, department_id) values ('Chef Hat 20cm', 3);
insert into product (name, department_id) values ('Plums - Red', 6);
insert into product (name, department_id) values ('Lemon Tarts', 5);
insert into product (name, department_id) values ('Lemonade - Mandarin, 591 Ml', 6);
insert into product (name, department_id) values ('Tomato - Green', 5);
insert into product (name, department_id) values ('Bols Melon Liqueur', 8);
insert into product (name, department_id) values ('Beef - Prime Rib Aaa', 9);
insert into product (name, department_id) values ('Salmon Steak - Cohoe 8 Oz', 7);
insert into product (name, department_id) values ('Drambuie', 1);
insert into product (name, department_id) values ('Miso - Soy Bean Paste', 2);
insert into product (name, department_id) values ('Plate - Foam, Bread And Butter', 8);
insert into product (name, department_id) values ('Tea Leaves - Oolong', 2);
insert into product (name, department_id) values ('Butter - Unsalted', 3);
insert into product (name, department_id) values ('Glove - Cutting', 2);
insert into product (name, department_id) values ('Crab Brie In Phyllo', 9);
insert into product (name, department_id) values ('Pears - Fiorelle', 3);
insert into product (name, department_id) values ('Mustard - Dry, Powder', 7);
insert into product (name, department_id) values ('Flavouring - Orange', 8);
insert into product (name, department_id) values ('Chicken - Wings, Tip Off', 9);
insert into product (name, department_id) values ('Creme De Banane - Marie', 9);
insert into product (name, department_id) values ('Table Cloth 62x114 Colour', 2);
insert into product (name, department_id) values ('Bar - Granola Trail Mix Fruit Nut', 8);
insert into product (name, department_id) values ('Oil - Food, Lacquer Spray', 1);
insert into product (name, department_id) values ('Veal - Bones', 6);
insert into product (name, department_id) values ('Wine - Champagne Brut Veuve', 9);
insert into product (name, department_id) values ('Pickle - Dill', 6);
insert into product (name, department_id) values ('Pork - Shoulder', 4);
insert into product (name, department_id) values ('Table Cloth 90x90 Colour', 5);
insert into product (name, department_id) values ('Parasol Pick Stir Stick', 5);
insert into product (name, department_id) values ('Nantucket - Orange Mango Cktl', 2);
insert into product (name, department_id) values ('Curry Paste - Green Masala', 6);
insert into product (name, department_id) values ('Pasta - Lasagna Noodle, Frozen', 6);
insert into product (name, department_id) values ('Dates', 2);
insert into product (name, department_id) values ('Arctic Char - Fresh, Whole', 7);
insert into product (name, department_id) values ('Soup - Campbells Bean Medley', 8);
insert into product (name, department_id) values ('Bulgar', 4);
insert into product (name, department_id) values ('Black Currants', 4);
insert into product (name, department_id) values ('Lamb Leg - Bone - In Nz', 4);
insert into product (name, department_id) values ('Oil - Grapeseed Oil', 9);
insert into product (name, department_id) values ('Bagel - 12 Grain Preslice', 9);
insert into product (name, department_id) values ('Calaloo', 7);
insert into product (name, department_id) values ('Anchovy Fillets', 9);
insert into product (name, department_id) values ('Bagels Poppyseed', 1);
insert into product (name, department_id) values ('Pastry - Carrot Muffin - Mini', 1);
insert into product (name, department_id) values ('Muffin Puck Ww Carrot', 6);
insert into product (name, department_id) values ('Beer - Maudite', 9);
insert into product (name, department_id) values ('Flower - Carnations', 5);
insert into product (name, department_id) values ('Chicken Breast Wing On', 3);
insert into product (name, department_id) values ('Coffee - French Vanilla Frothy', 4);
insert into product (name, department_id) values ('Cleaner - Bleach', 1);
insert into product (name, department_id) values ('Soup - Knorr, Chicken Noodle', 7);
insert into product (name, department_id) values ('Syrup - Monin - Passion Fruit', 9);
insert into product (name, department_id) values ('Yoplait Drink', 1);
insert into product (name, department_id) values ('Cookie Dough - Double', 9);
insert into product (name, department_id) values ('Food Colouring - Orange', 1);
insert into product (name, department_id) values ('Soup - Campbells, Creamy', 8);
insert into product (name, department_id) values ('Parsley - Dried', 2);
insert into product (name, department_id) values ('Nut - Pumpkin Seeds', 6);
insert into product (name, department_id) values ('Otomegusa Dashi Konbu', 4);
insert into product (name, department_id) values ('Venison - Denver Leg Boneless', 4);
insert into product (name, department_id) values ('Bread - Onion Focaccia', 1);
insert into product (name, department_id) values ('Tomatoes - Cherry', 4);
insert into product (name, department_id) values ('Steampan - Half Size Shallow', 8);
insert into product (name, department_id) values ('Wine - White, Concha Y Toro', 6);
insert into product (name, department_id) values ('Chicken - White Meat, No Tender', 9);
insert into product (name, department_id) values ('Wine - Remy Pannier Rose', 3);
insert into product (name, department_id) values ('Shallots', 3);
insert into product (name, department_id) values ('Gelatine Powder', 3);
insert into product (name, department_id) values ('Beans - Black Bean, Canned', 2);
insert into product (name, department_id) values ('Doilies - 10, Paper', 9);
insert into product (name, department_id) values ('Nut - Hazelnut, Whole', 7);
insert into product (name, department_id) values ('Pasta - Fettuccine, Egg, Fresh', 8);
insert into product (name, department_id) values ('Cheese - Cambozola', 7);
insert into product (name, department_id) values ('Beef - Montreal Smoked Brisket', 3);
insert into product (name, department_id) values ('Swiss Chard - Red', 7);
insert into product (name, department_id) values ('Carrots - Mini Red Organic', 7);
insert into product (name, department_id) values ('Flour - Pastry', 9);
insert into product (name, department_id) values ('Yams', 3);
insert into product (name, department_id) values ('Mushroom - King Eryingii', 5);
insert into product (name, department_id) values ('Veal - Liver', 5);
insert into product (name, department_id) values ('Beef - Roasted, Cooked', 2);
insert into product (name, department_id) values ('Cape Capensis - Fillet', 6);
insert into product (name, department_id) values ('Aspic - Light', 5);
insert into product (name, department_id) values ('V8 - Berry Blend', 2);
insert into product (name, department_id) values ('Cheese - Roquefort Pappillon', 6);
insert into product (name, department_id) values ('Wine - White, Riesling, Henry Of', 3);
insert into product (name, department_id) values ('Butter Sweet', 7);
insert into product (name, department_id) values ('Cake - Bande Of Fruit', 8);
insert into product (name, department_id) values ('Chicken - Whole Roasting', 1);
insert into product (name, department_id) values ('Tequila Rose Cream Liquor', 4);
insert into product (name, department_id) values ('Syrup - Monin - Granny Smith', 8);
insert into product (name, department_id) values ('Rice - Aborio', 1);
insert into product (name, department_id) values ('Wine La Vielle Ferme Cote Du', 5);
insert into product (name, department_id) values ('Nestea - Ice Tea, Diet', 5);
insert into product (name, department_id) values ('Flour - Strong', 4);
insert into product (name, department_id) values ('Wine - Sawmill Creek Autumn', 6);
insert into product (name, department_id) values ('Cloves - Ground', 9);
insert into product (name, department_id) values ('Paper - Brown Paper Mini Cups', 2);
insert into product (name, department_id) values ('Madeira', 8);
insert into product (name, department_id) values ('Muffin Batt - Carrot Spice', 2);
insert into product (name, department_id) values ('Cake Circle, Foil, Scallop', 4);
insert into product (name, department_id) values ('Lumpfish Black', 6);
insert into product (name, department_id) values ('Clam - Cherrystone', 7);
insert into product (name, department_id) values ('Kolrabi', 3);
insert into product (name, department_id) values ('Glycerine', 2);
insert into product (name, department_id) values ('Sterno - Chafing Dish Fuel', 9);
insert into product (name, department_id) values ('Mayonnaise - Individual Pkg', 1);
insert into product (name, department_id) values ('General Purpose Trigger', 9);
insert into product (name, department_id) values ('Sprite - 355 Ml', 9);
insert into product (name, department_id) values ('Cheese - Victor Et Berthold', 7);
insert into product (name, department_id) values ('Tomato Paste', 3);
insert into product (name, department_id) values ('Capon - Whole', 2);
insert into product (name, department_id) values ('Mushroom - Portebello', 9);
insert into product (name, department_id) values ('Lamb - Racks, Frenched', 2);
insert into product (name, department_id) values ('Bar Energy Chocchip', 6);
insert into product (name, department_id) values ('Sauce Tomato Pouch', 3);
insert into product (name, department_id) values ('Glaze - Apricot', 1);
insert into product (name, department_id) values ('Vaccum Bag - 14x20', 8);
insert into product (name, department_id) values ('Shrimp - 16/20, Iqf, Shell On', 7);
insert into product (name, department_id) values ('Beets - Mini Golden', 6);
insert into product (name, department_id) values ('Absolut Citron', 4);
insert into product (name, department_id) values ('Soup Campbells Mexicali Tortilla', 7);
insert into product (name, department_id) values ('Shrimp - 16/20, Peeled Deviened', 8);
insert into product (name, department_id) values ('Nantucket Orange Juice', 5);
insert into product (name, department_id) values ('Assorted Desserts', 4);
insert into product (name, department_id) values ('Wine - Chateau Aqueria Tavel', 8);
insert into product (name, department_id) values ('Tart Shells - Sweet, 4', 2);
insert into product (name, department_id) values ('Ecolab - Ster Bac', 9);
insert into product (name, department_id) values ('Shopper Bag - S - 4', 3);
insert into product (name, department_id) values ('Red Currant Jelly', 6);
insert into product (name, department_id) values ('Maintenance Removal Charge', 8);
insert into product (name, department_id) values ('Rum - White, Gg White', 7);
insert into product (name, department_id) values ('Sausage - Breakfast', 5);
insert into product (name, department_id) values ('Haggis', 1);
insert into product (name, department_id) values ('Spice - Onion Powder Granulated', 1);
insert into product (name, department_id) values ('Bag - Bread, White, Plain', 8);
insert into product (name, department_id) values ('Tea - Camomele', 3);
insert into product (name, department_id) values ('Wine - Rioja Campo Viejo', 7);
insert into product (name, department_id) values ('Rabbit - Legs', 8);
insert into product (name, department_id) values ('Hog / Sausage Casing - Pork', 3);
insert into product (name, department_id) values ('Scrubbie - Scotchbrite Hand Pad', 3);
insert into product (name, department_id) values ('Maple Syrup', 2);
insert into product (name, department_id) values ('Wine - Pinot Noir Latour', 2);
insert into product (name, department_id) values ('Juice - Cranberry, 341 Ml', 7);
insert into product (name, department_id) values ('Bacardi Raspberry', 5);
insert into product (name, department_id) values ('Lettuce - Red Leaf', 5);
insert into product (name, department_id) values ('Juice - Pineapple, 48 Oz', 8);
insert into product (name, department_id) values ('Bread - 10 Grain', 4);
insert into product (name, department_id) values ('Figs', 5);
insert into product (name, department_id) values ('Hand Towel', 3);
insert into product (name, department_id) values ('Soup - Campbells, Spinach Crm', 7);
insert into product (name, department_id) values ('Wine - Wyndham Estate Bin 777', 7);
insert into product (name, department_id) values ('Tomato - Plum With Basil', 2);
insert into product (name, department_id) values ('Soup - Campbells Mushroom', 8);
insert into product (name, department_id) values ('Chocolate - Unsweetened', 9);
insert into product (name, department_id) values ('Corn Meal', 4);
insert into product (name, department_id) values ('French Pastries', 3);
insert into product (name, department_id) values ('Chocolate - Milk Coating', 1);
insert into product (name, department_id) values ('Cheese - Havarti, Roasted Garlic', 7);
insert into product (name, department_id) values ('Avocado', 1);
insert into product (name, department_id) values ('Compound - Rum', 2);
insert into product (name, department_id) values ('Nut - Pecan, Halves', 9);
insert into product (name, department_id) values ('Soup - Knorr, Chicken Gumbo', 9);
insert into product (name, department_id) values ('Soap - Mr.clean Floor Soap', 5);
insert into product (name, department_id) values ('Lamb - Leg, Boneless', 8);
insert into product (name, department_id) values ('Wine - Red, Antinori Santa', 9);
insert into product (name, department_id) values ('Tomatoes - Roma', 3);
insert into product (name, department_id) values ('Beef - Short Ribs', 6);
insert into product (name, department_id) values ('Tomatoes - Diced, Canned', 5);
insert into product (name, department_id) values ('Juice - Pineapple, 341 Ml', 1);
insert into product (name, department_id) values ('Beans - Kidney, Red Dry', 7);
insert into product (name, department_id) values ('Compound - Orange', 2);
insert into product (name, department_id) values ('Bread - Hot Dog Buns', 1);
insert into product (name, department_id) values ('Sun - Dried Tomatoes', 7);
insert into product (name, department_id) values ('Wine - Cabernet Sauvignon', 1);
insert into product (name, department_id) values ('Buffalo - Short Rib Fresh', 1);
insert into product (name, department_id) values ('Asparagus - Mexican', 3);
insert into product (name, department_id) values ('White Baguette', 8);
insert into product (name, department_id) values ('Sprouts Dikon', 5);
insert into product (name, department_id) values ('Lamb - Pieces, Diced', 2);
insert into product (name, department_id) values ('Compound - Passion Fruit', 8);
insert into product (name, department_id) values ('Seaweed Green Sheets', 1);
insert into product (name, department_id) values ('Beef Ground Medium', 6);
insert into product (name, department_id) values ('Beef - Ground Lean Fresh', 3);
insert into product (name, department_id) values ('Garam Marsala', 7);
insert into product (name, department_id) values ('Beans - French', 8);
insert into product (name, department_id) values ('Tomatillo', 5);
insert into product (name, department_id) values ('Bouq All Italian - Primerba', 5);
insert into product (name, department_id) values ('Spinach - Packaged', 4);
insert into product (name, department_id) values ('Flower - Commercial Spider', 5);
insert into product (name, department_id) values ('Vinegar - Raspberry', 4);
insert into product (name, department_id) values ('Lettuce - Lambs Mash', 9);
insert into product (name, department_id) values ('Cheese - Shred Cheddar / Mozza', 8);
insert into product (name, department_id) values ('Shrimp - 21/25, Peel And Deviened', 7);
insert into product (name, department_id) values ('Lettuce - Curly Endive', 4);
insert into product (name, department_id) values ('Loquat', 7);
insert into product (name, department_id) values ('Miso Paste White', 6);
insert into product (name, department_id) values ('Flour - Semolina', 3);
insert into product (name, department_id) values ('Sage - Ground', 3);
insert into product (name, department_id) values ('Numi - Assorted Teas', 8);
insert into product (name, department_id) values ('Salmon - Smoked, Sliced', 6);
insert into product (name, department_id) values ('V8 - Tropical Blend', 8);
insert into product (name, department_id) values ('Table Cloth 120 Round White', 3);
insert into product (name, department_id) values ('Nut - Almond, Blanched, Whole', 7);
insert into product (name, department_id) values ('Chinese Foods - Pepper Beef', 5);
insert into product (name, department_id) values ('Flour - Masa De Harina Mexican', 2);
insert into product (name, department_id) values ('Wine - Two Oceans Sauvignon', 5);
insert into product (name, department_id) values ('Glucose', 7);
insert into product (name, department_id) values ('Hipnotiq Liquor', 4);
insert into product (name, department_id) values ('Juice - Orange', 8);
insert into product (name, department_id) values ('Shichimi Togarashi Peppeers', 4);
insert into product (name, department_id) values ('Burger Veggie', 9);
insert into product (name, department_id) values ('Ecolab - Hobart Washarm End Cap', 5);
insert into product (name, department_id) values ('Nantucket - 518ml', 2);
insert into product (name, department_id) values ('Longos - Chicken Cordon Bleu', 8);
insert into product (name, department_id) values ('Bacardi Limon', 2);
insert into product (name, department_id) values ('Veal - Leg, Provimi - 50 Lb Max', 8);
insert into product (name, department_id) values ('Longos - Penne With Pesto', 6);
insert into product (name, department_id) values ('Chutney Sauce - Mango', 7);
insert into product (name, department_id) values ('Creme De Menth - White', 6);
insert into product (name, department_id) values ('Bread - Hamburger Buns', 2);
insert into product (name, department_id) values ('Mushroom - Crimini', 2);
insert into product (name, department_id) values ('Garam Masala Powder', 7);
insert into product (name, department_id) values ('Crackers - Graham', 3);
insert into product (name, department_id) values ('Lamb Tenderloin Nz Fr', 6);
insert into product (name, department_id) values ('Wine - Valpolicella Masi', 3);
insert into product (name, department_id) values ('Uniform Linen Charge', 3);
insert into product (name, department_id) values ('Buffalo - Tenderloin', 4);
insert into product (name, department_id) values ('Pie Pecan', 6);
insert into product (name, department_id) values ('Pepper - Black, Crushed', 3);
insert into product (name, department_id) values ('Steam Pan - Half Size Deep', 5);
insert into product (name, department_id) values ('Kumquat', 1);
insert into product (name, department_id) values ('Turnip - White', 3);
insert into product (name, department_id) values ('Straw - Regular', 9);
insert into product (name, department_id) values ('Wine - Duboeuf Beaujolais', 8);
insert into product (name, department_id) values ('Wine - Pinot Noir Pond Haddock', 9);
insert into product (name, department_id) values ('Potatoes - Idaho 80 Count', 8);
insert into product (name, department_id) values ('Pepper - Orange', 3);
insert into product (name, department_id) values ('Mace Ground', 5);
insert into product (name, department_id) values ('Goat - Leg', 4);
insert into product (name, department_id) values ('Wine - Winzer Krems Gruner', 5);
insert into product (name, department_id) values ('Wine - Alsace Gewurztraminer', 5);
insert into product (name, department_id) values ('Water - Evian 355 Ml', 3);
insert into product (name, department_id) values ('Oil - Margarine', 5);
insert into product (name, department_id) values ('Wine - Crozes Hermitage E.', 6);
insert into product (name, department_id) values ('Sugar - Brown, Individual', 7);
insert into product (name, department_id) values ('Herb Du Provence - Primerba', 5);
insert into product (name, department_id) values ('Dish Towel', 1);
insert into product (name, department_id) values ('Tomato Puree', 6);
insert into product (name, department_id) values ('Schnappes Peppermint - Walker', 2);
insert into product (name, department_id) values ('Pizza Pizza Dough', 7);
insert into product (name, department_id) values ('Sparkling Wine - Rose, Freixenet', 4);
insert into product (name, department_id) values ('Beef - Shank', 3);
insert into product (name, department_id) values ('Coffee - 10oz Cup 92961', 7);
insert into product (name, department_id) values ('Soup - Campbells Asian Noodle', 1);
insert into product (name, department_id) values ('Yogurt - Peach, 175 Gr', 5);
insert into product (name, department_id) values ('Clementine', 4);
insert into product (name, department_id) values ('Tilapia - Fillets', 4);
insert into product (name, department_id) values ('Juice - Orange 1.89l', 6);
insert into product (name, department_id) values ('Cookie Dough - Chunky', 9);
insert into product (name, department_id) values ('Compound - Mocha', 5);
insert into product (name, department_id) values ('Garbage Bags - Clear', 5);
insert into product (name, department_id) values ('Puff Pastry - Sheets', 9);
insert into product (name, department_id) values ('Butter - Pod', 2);
insert into product (name, department_id) values ('Nantucket - Kiwi Berry Cktl.', 9);
insert into product (name, department_id) values ('Dc - Frozen Momji', 2);
insert into product (name, department_id) values ('Wine - White, Lindemans Bin 95', 6);
insert into product (name, department_id) values ('Truffle Cups - Red', 6);
insert into product (name, department_id) values ('Beef - Top Sirloin - Aaa', 4);
insert into product (name, department_id) values ('Juice - Lemon', 1);
insert into product (name, department_id) values ('Yucca', 6);
insert into product (name, department_id) values ('Octopus - Baby, Cleaned', 7);
insert into product (name, department_id) values ('Brownies - Two Bite, Chocolate', 8);
insert into product (name, department_id) values ('Duck - Fat', 8);
insert into product (name, department_id) values ('Lamb - Leg, Diced', 5);
insert into product (name, department_id) values ('Wine - Red, Marechal Foch', 3);
insert into product (name, department_id) values ('Kale - Red', 6);
insert into product (name, department_id) values ('Island Oasis - Magarita Mix', 2);
insert into product (name, department_id) values ('Carbonated Water - Wildberry', 8);
insert into product (name, department_id) values ('Wine - Pinot Noir Stoneleigh', 9);
insert into product (name, department_id) values ('Corn - Cream, Canned', 4);
insert into product (name, department_id) values ('Cloves - Whole', 9);
insert into product (name, department_id) values ('Beef - Ox Tongue', 7);
insert into product (name, department_id) values ('Cake Circle, Paprus', 5);
insert into product (name, department_id) values ('Swordfish Loin Portions', 2);
insert into product (name, department_id) values ('Wine - Red, Pinot Noir, Chateau', 5);
insert into product (name, department_id) values ('Lettuce - Green Leaf', 9);
insert into product (name, department_id) values ('Table Cloth 81x81 Colour', 1);
insert into product (name, department_id) values ('Soup Bowl Clear 8oz92008', 1);
insert into product (name, department_id) values ('Vaccum Bag 10x13', 4);
insert into product (name, department_id) values ('Buffalo - Striploin', 8);
insert into product (name, department_id) values ('Venison - Liver', 9);
insert into product (name, department_id) values ('Muffin Mix - Oatmeal', 8);
insert into product (name, department_id) values ('Pork - Tenderloin, Fresh', 4);
insert into product (name, department_id) values ('Calypso - Strawberry Lemonade', 8);
insert into product (name, department_id) values ('Basil - Seedlings Cookstown', 7);
insert into product (name, department_id) values ('Jameson Irish Whiskey', 8);
insert into product (name, department_id) values ('Lamb - Bones', 9);
insert into product (name, department_id) values ('Cake - Box Window 10x10x2.5', 5);
insert into product (name, department_id) values ('Lamb Shoulder Boneless Nz', 3);
insert into product (name, department_id) values ('Sesame Seed', 3);
insert into product (name, department_id) values ('Flower - Daisies', 5);
insert into product (name, department_id) values ('Wine - Tio Pepe Sherry Fino', 8);
insert into product (name, department_id) values ('Cafe Royale', 4);
insert into product (name, department_id) values ('Sambuca - Opal Nera', 9);
insert into product (name, department_id) values ('Fiddlehead - Frozen', 7);
insert into product (name, department_id) values ('Wine - Zonnebloem Pinotage', 9);
insert into product (name, department_id) values ('Wine - Chianti Classica Docg', 6);
insert into product (name, department_id) values ('Pop - Club Soda Can', 2);
insert into product (name, department_id) values ('Olives - Stuffed', 5);
insert into product (name, department_id) values ('Mcgillicuddy Vanilla Schnap', 4);
insert into product (name, department_id) values ('Soup - Cream Of Broccoli, Dry', 7);
insert into product (name, department_id) values ('Veal - Loin', 4);
insert into product (name, department_id) values ('Artichoke - Hearts, Canned', 8);
insert into product (name, department_id) values ('Cheese - Ermite Bleu', 2);
insert into product (name, department_id) values ('Thyme - Fresh', 6);
insert into product (name, department_id) values ('Puree - Raspberry', 6);
insert into product (name, department_id) values ('Crab Meat Claw Pasteurise', 9);
insert into product (name, department_id) values ('Sauce - Ranch Dressing', 7);
insert into product (name, department_id) values ('Beer - Tetleys', 2);
insert into product (name, department_id) values ('Kiwi Gold Zespri', 8);
insert into product (name, department_id) values ('Sherbet - Raspberry', 8);
insert into product (name, department_id) values ('Calvados - Boulard', 7);
insert into product (name, department_id) values ('Flour Pastry Super Fine', 3);
insert into product (name, department_id) values ('Wine - Kwv Chenin Blanc South', 8);
insert into product (name, department_id) values ('Bread - Roll, Calabrese', 9);
insert into product (name, department_id) values ('Lotus Leaves', 7);
insert into product (name, department_id) values ('Hot Choc Vending', 5);
insert into product (name, department_id) values ('Wine - White, Gewurtzraminer', 3);
insert into product (name, department_id) values ('Gingerale - Schweppes, 355 Ml', 9);
insert into product (name, department_id) values ('Fruit Salad Deluxe', 5);
insert into product (name, department_id) values ('Wine - Penfolds Koonuga Hill', 9);
insert into product (name, department_id) values ('Muffin Batt - Choc Chk', 3);
insert into product (name, department_id) values ('Potatoes - Purple, Organic', 5);
insert into product (name, department_id) values ('Salad Dressing', 3);
insert into product (name, department_id) values ('Pasta - Rotini, Dry', 9);
insert into product (name, department_id) values ('Iced Tea Concentrate', 9);
insert into product (name, department_id) values ('Rosemary - Fresh', 2);
insert into product (name, department_id) values ('Mangostein', 5);
insert into product (name, department_id) values ('Snapple Lemon Tea', 8);
insert into product (name, department_id) values ('Pork - Belly Fresh', 8);
insert into product (name, department_id) values ('Cheese - St. Andre', 4);
insert into product (name, department_id) values ('Pastry - Butterscotch Baked', 2);
insert into product (name, department_id) values ('Nantuket Peach Orange', 9);
insert into product (name, department_id) values ('Wine - Casablanca Valley', 4);
insert into product (name, department_id) values ('Bread - Calabrese Baguette', 6);
insert into product (name, department_id) values ('Ocean Spray - Ruby Red', 9);
insert into product (name, department_id) values ('Pumpkin', 8);
insert into product (name, department_id) values ('Sprite, Diet - 355ml', 3);
insert into product (name, department_id) values ('Squash - Pepper', 3);
insert into product (name, department_id) values ('Gelatine Leaves - Bulk', 2);
insert into product (name, department_id) values ('Cookies - Englishbay Oatmeal', 7);
insert into product (name, department_id) values ('Beer - Pilsner Urquell', 1);
insert into product (name, department_id) values ('Pork - Hock And Feet Attached', 1);
insert into product (name, department_id) values ('Bread - Roll, Whole Wheat', 7);
insert into product (name, department_id) values ('Soup - Canadian Pea, Dry Mix', 1);
insert into product (name, department_id) values ('Gatorade - Lemon Lime', 6);
insert into product (name, department_id) values ('Barley - Pearl', 8);
insert into product (name, department_id) values ('Lettuce - Spring Mix', 2);
insert into product (name, department_id) values ('Wine - Magnotta, White', 7);
insert into product (name, department_id) values ('Truffle - Whole Black Peeled', 1);
insert into product (name, department_id) values ('Appetizer - Asian Shrimp Roll', 6);
insert into product (name, department_id) values ('Sprouts - Alfalfa', 8);
insert into product (name, department_id) values ('Paste - Black Olive', 7);
insert into product (name, department_id) values ('Pastry - Plain Baked Croissant', 3);
insert into product (name, department_id) values ('Clams - Bay', 2);
insert into product (name, department_id) values ('Beef - Salted', 9);
insert into product (name, department_id) values ('Russian Prince', 3);
insert into product (name, department_id) values ('Wine - Rosso Del Veronese Igt', 7);
insert into product (name, department_id) values ('Sauce - Marinara', 9);
insert into product (name, department_id) values ('Shrimp - 31/40', 8);
insert into product (name, department_id) values ('Milk - Buttermilk', 7);
insert into product (name, department_id) values ('Sage - Fresh', 5);
insert into product (name, department_id) values ('Ginger - Crystalized', 7);
insert into product (name, department_id) values ('Cheese - Valancey', 7);
insert into product (name, department_id) values ('Island Oasis - Ice Cream Mix', 8);
insert into product (name, department_id) values ('Wine - Niagara Peninsula Vqa', 8);
insert into product (name, department_id) values ('Crackers - Melba Toast', 6);
insert into product (name, department_id) values ('Garbage Bag - Clear', 6);
insert into product (name, department_id) values ('Spinach - Spinach Leaf', 9);
insert into product (name, department_id) values ('Pasta - Ravioli', 3);
insert into product (name, department_id) values ('Pike - Frozen Fillet', 3);
insert into product (name, department_id) values ('Nut - Chestnuts, Whole', 9);
insert into product (name, department_id) values ('Mushroom - Morel Frozen', 9);
